# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
